FROM maven:3.9.6-eclipse-temurin-17 AS build
WORKDIR /app
COPY pom.xml .
RUN mvn -q -e -DskipTests dependency:go-offline
COPY src ./src
RUN mvn -q -DskipTests package

FROM eclipse-temurin:17-jre
WORKDIR /app
ENV JAVA_OPTS=""
COPY --from=build /app/target/micro-community-1.0.0.jar app.jar
EXPOSE 8080
ENTRYPOINT [\"sh\",\"-c\",\"java \$JAVA_OPTS -jar app.jar\"]
